const pw = (await import(process.env.VQ_PW ?? '/opt/node22/lib/node_modules/playwright/index.js')).default;
const { chromium } = pw;
const S=new URL('./_out', import.meta.url).pathname;
const b=await chromium.launch({executablePath:process.env.VQ_CHROME ?? '/opt/pw-browsers/chromium-1194/chrome-linux/chrome',args:['--no-sandbox']});
const c=await b.newContext({viewport:{width:430,height:900},deviceScaleFactor:2});
const p=await c.newPage();
const errs=[]; p.on('pageerror',e=>errs.push(e.message));
await p.goto(new URL('../index.html', import.meta.url).href,{waitUntil:'load'});
await p.evaluate(()=>{ document.getElementById('loginLayer').classList.add('off'); });
await p.waitForTimeout(2600);
await p.click('#btnAvatarPerfil'); await p.waitForTimeout(500);
await p.evaluate(()=>{ document.getElementById('v-aluno').scrollTop=0; });
await p.waitForTimeout(400);
const el=await p.$('.phone'); await el.screenshot({path:S+'/rank-card.png'});
console.log('erros:', errs.length?errs.join('|'):'nenhum');
await b.close();
